-- Run this script in your Supabase SQL Editor

CREATE TABLE competitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  start_date DATE,
  location TEXT,
  deadline DATE,
  fee TEXT,
  url TEXT,
  description TEXT,
  age_group TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'declined')),
  approval_token TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: In a real environment, you might want to enable Row Level Security (RLS)
-- and add policies, but for this simple public viewer / internal scraper setup, 
-- you can leave it accessible via service_role key for the scraper.
